version: "3.3"
#https://hub.docker.com/_/influxdb

services:
  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - 8086:8086
    volumes:
      - "./influxdb2:/var/lib/influxdb2"

  grafana:
    image: grafana/grafana
    restart: always
    ports: 
      - 3001:3000